version: '3.4'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
  login:
    build: ./login
    ports:
      - "1234:1234"
  db:
    build: ./db
    ports:
      - "3001:3001"


