version: '3.4'

services:
  login:
    image: login
    build:
      context: login
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 1234:1234
